# =========================
# Worker OCI (rootlesskit)
# =========================
[worker.oci]
  enabled = true
  rootless = true
  no-process-sandbox = true
  snapshotter = "overlayfs"   # usa overlayfs se il kernel lo consente

[worker.containerd]
  enabled = false

# =========================
# Registry HTTP insicuro
# =========================
[registry."nuvolaris-registry-svc:5000"]
  insecure = true
  http = true

# =========================
# Logging
# =========================
[log]
  level = "debug"